#! /usr/bin/python3
# -*- coding: utf-8 -*-
import subprocess
from pathlib import Path
from functools import cache
import sys


@cache
def linux_in_wsl2() -> bool:
    res = shell("uname -a", capture_output=True)
    return "MICROSOFT" in res.stdout.upper()


def shell(cmd: str, capture_output: bool = False) -> subprocess.CompletedProcess[str]:
    kwargs = {}
    if capture_output:
        kwargs["capture_output"] = True
        kwargs["text"] = True
    return subprocess.run(cmd, shell=True, **kwargs)


def startup():
    print("\n>> Starting KinD and Registry...")
    cmd = str(
        Path(__file__).joinpath("..", "script", "kind-with-registry.sh").resolve()
    )
    shell(cmd)

    print("\n>> Starting LoadBalancer...")
    cmd = "kubectl label node kind-control-plane node.kubernetes.io/exclude-from-external-load-balancers-"
    shell(cmd)
    res = shell("which cloud-provider-kind", capture_output=True)
    cmd = ("sudo " if linux_in_wsl2() else "") + res.stdout.strip()
    shell(cmd)


def shutdown():
    print(">> Finished LoadBalancer!")
    print("\n>> Finishing KinD and Registry...")
    shell("kind delete cluster")
    shell("docker rm -f kind-registry")
    print(">> Finished KinD and Registry!")


def main():
    if linux_in_wsl2():
        res = shell("sudo printf ''")
        if res.returncode == 1:
            sys.exit("\n>> Error: Permission denied! Please run as sudo.")

    print("# STARTING LOCAL KUBERNETES")
    try:
        startup()
    except KeyboardInterrupt:
        pass
    shutdown()
    print("\n# FINISHED LOCAL KUBERNETES")


if __name__ == "__main__":
    main()
