#! /usr/bin/python3
# -*- coding: utf-8 -*-
import subprocess
import sys
from functools import cache
from pathlib import Path


@cache
def is_linux_native() -> bool:
    res = shell("uname -a", capture_output=True)
    if "LINUX" in str(sys.platform).upper():
        if "MICROSOFT" in res.stdout.upper():
            return False
        return True
    return False


@cache
def get_container_runtime() -> str:
    if shell("which docker", capture_output=True).returncode == 0:
        return "docker"
    elif shell("which podman", capture_output=True).returncode == 0:
        return "podman"
    raise Exception("No container runtime found! Please install Docker or Podman.")


def shell(cmd: str, capture_output: bool = False) -> subprocess.CompletedProcess[str]:
    kwargs = {}
    if capture_output:
        kwargs["capture_output"] = True
        kwargs["text"] = True
    return subprocess.run(cmd, shell=True, **kwargs)


def startup():
    print("\n>> Starting KinD and Registry...")
    cmd = str(
        Path(__file__).joinpath("..", "script", "kind-with-registry.sh").resolve()
    )
    shell(cmd)
    print(f"\n>> Starting LoadBalancer... {'' if is_linux_native() else '(#)'}")
    cmd = "kubectl label node kind-control-plane node.kubernetes.io/exclude-from-external-load-balancers-"
    shell(cmd)
    res = shell("which cloud-provider-kind", capture_output=True)
    cmd = (
        ("" if is_linux_native() else "sudo ")
        + res.stdout.strip()
    )
    shell(cmd)


def shutdown():
    print(">> Finished LoadBalancer!")
    print("\n>> Finishing KinD and Registry...")
    shell("kind delete cluster")
    shell(f"{get_container_runtime()} rm -f kind-registry")
    print(">> Finished KinD and Registry!")


def main():
    if not is_linux_native():
        res = shell("sudo printf ''")
        if res.returncode == 1:
            sys.exit("\n>> Error: Permission denied! Please run as sudo.")

    print("# STARTING LOCAL KUBERNETES")
    try:
        startup()
    except KeyboardInterrupt:
        pass
    shutdown()
    print("\n# FINISHED LOCAL KUBERNETES")


if __name__ == "__main__":
    main()
